# Generated by Django 4.1.2 on 2022-10-24 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varlmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursestaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'coursestaken',
                'db_table': 'coursestaken',
            },
        ),
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'lessons',
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='quiztaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'quiztaken',
                'db_table': 'quiztaken',
            },
        ),
        migrations.CreateModel(
            name='quiztopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varlmsapp.lessons')),
            ],
            options={
                'verbose_name_plural': 'quiztopic',
                'db_table': 'quiztopic',
            },
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_result',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_result',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.DeleteModel(
            name='lesson',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.DeleteModel(
            name='quiz_question',
        ),
        migrations.DeleteModel(
            name='quiz_result',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='quiztopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varlmsapp.quiztopic'),
        ),
        migrations.AddField(
            model_name='quiztaken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessons',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varlmsapp.course'),
        ),
        migrations.AddField(
            model_name='coursestaken',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varlmsapp.course'),
        ),
        migrations.AddField(
            model_name='coursestaken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
