# Generated by Django 4.1.2 on 2022-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varlmsapp', '0002_coursestaken_lessons_quiztaken_quiztopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lessonname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
