# Generated by Django 4.1.2 on 2022-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varlmsapp', '0004_quiztopic_answer_quiztopic_options1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='varlmsapp.lessons'),
        ),
    ]
