# Generated by Django 3.1.3 on 2022-10-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varlmsapp', '0006_auto_20221027_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
    ]
