# Generated by Django 3.1.3 on 2022-11-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varlmsapp', '0008_auto_20221027_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'quiz',
                'db_table': 'quiz',
            },
        ),
        migrations.RemoveField(
            model_name='quiztopic',
            name='name',
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='varlmsapp.Lessons'),
        ),
        migrations.DeleteModel(
            name='quiztaken',
        ),
        migrations.DeleteModel(
            name='quiztopic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varlmsapp.lessons'),
        ),
    ]
