# Generated by Django 3.1.3 on 2022-11-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varlmsapp', '0009_auto_20221101_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='varlmsapp.Lessons'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100))], max_length=100),
        ),
    ]
